#+TITLE: Emacs Configuration
#+PROPERTY: header-args :tangle init.el


* Preamble
** Sources
;; Configuration for Todd Suomela
;;   I'm trying to do a setup from scratch and just add packages as I find or need them.
;;   Started in Feb / March 2025
;; First source is:
;;   starting with stuff from daviwill/emacs-from-scratch on github
;;   Then more stuff from Prot

* Package Managment
Setting up package sources from Melpa, ormode, and elpa.

#+begin_src emacs-lisp
;;--------- Package Management
;; Initialize package sources
(require 'package)

(setq package-archives '(("melpa" . "https://melpa.org/packages/")
                         ("org" . "https://orgmode.org/elpa/")
                         ("elpa" . "https://elpa.gnu.org/packages/")))

(package-initialize)
(unless package-archive-contents
 (package-refresh-contents))

;; Initialize use-package on non-Linux platforms
(unless (package-installed-p 'use-package)
   (package-install 'use-package))

(require 'use-package)
(setq use-package-always-ensure t)
#+end_src

* Custom File Location
#+begin_src emacs-lisp

;;--------- Custom file settings
;; Set location for custom.el information
(setq custom-file (expand-file-name "custom.el" user-emacs-directory))
(when (file-exists-p custom-file)
  (load custom-file))
#+end_src

* Appearance
** Miscellaneous Items
Menu bar, toolbar, tooltips, etc.
#+begin_src emacs-lisp

  ;;--------- Appearance
  ;; font settins and fontaine package setup
  (setq inhibit-startup-message t)
  (scroll-bar-mode -1)        ; Disable visible scrollbar
  (tool-bar-mode -1)          ; Disable the toolbar
  (tooltip-mode -1)           ; Disable tooltips
  (set-fringe-mode 10)        ; Give some breathing room
  (menu-bar-mode -1)          ; Disable the menu bar
  (setq visible-bell t)       ; visible-bell on
  (setq sentence-end-double-space nil) ; sentence boundaries
#+end_src

** Basic Font
I don't think I need this, but keep for now.
#+begin_src emacs-lisp

;; Set basic fonts and display theme
(set-face-attribute 'default nil
		    :family "Iosevka"
		    :height 160
		    :weight 'semi-light)
#+end_src

** Setting Theme
Using the modus themes.

#+begin_src emacs-lisp
(load-theme 'modus-operandi-tinted)
#+end_src

** Fontaine - Font Configuration

#+begin_src emacs-lisp

;;----------------------- display and fonts
;; fontaine - font management

(use-package fontaine
  :config
  (setq fontaine-presets
	'((regular :default-height 160)
	  (large :default-weight semilight
		 :default-height 190
		 :bold-weight extrabold)
	  (t :default-family "Iosevka"
	     :default-weight regular
	     :default-slant normal
	     :default-width normal
	     :default-height 120

	     :variable-pitch-family "ETBembo"
	     :variable-pitch-weight nil
	     :variable-pitch-slant nil
	     :variable-pitch-width nil
	     :variable-pitch-height 1.0))
	)
  ;; Set the last preset or fall back to desired style from `fontaine-presets'
  ;; (the `regular' in this case).
  (fontaine-set-preset (or (fontaine-restore-latest-preset) 'regular))

  ;; Persist the latest font preset when closing/starting Emacs and
  ;; while switching between themes.
  (fontaine-mode 1)
  )
#+end_src

** Mixed Pitch
for org mode
#+begin_src emacs-lisp

;; Mixed Pitch
(use-package mixed-pitch
  :hook
  ;; If you want it in all text modes:
  (text-mode . mixed-pitch-mode))
#+end_src

** Doom Themes
;; Doom Themes
;; (use-package doom-modeline
;;   :init
;;   (doom-modeline-mode 1)
;;   :custom
;;   ((doom-modeline-height 15)))

(use-package doom-themes)

** Rainbow Delimiters
#+begin_src emacs-lisp

(use-package rainbow-delimiters
  :hook
  (prog-mode . rainbow-delimiters-mode))
#+end_src

* Completion Framework
** Ivy - Dropped
;;--------- Completion
;; trying out ivy
;; ivy and counsel install
;; (use-package counsel
;;   :demand t
;;   :bind
;;   (("C-s" . swiper-isearch))
;;   :config
;;   (ivy-mode 1)
;;   (setq ivy-use-virtual-buffers t)
;;   (setq ivy-count-format "(%d/%d) "))

** Vertico

#+begin_src emacs-lisp

;; Enable Vertico.

(use-package vertico
  :demand t
  ;; :custom
  ;; (vertico-scroll-margin 0) ;; Different scroll margin
  ;; (vertico-count 20) ;; Show more candidates
  ;; (vertico-resize t) ;; Grow and shrink the Vertico minibuffer
  ;; (vertico-cycle t) ;; Enable cycling for `vertico-next/previous'
  :init
  (vertico-mode)
  (setq read-file-name-completion-ignore-case t
      read-buffer-completion-ignore-case t
      completion-ignore-case t))
#+end_src

*** History Sorting
#+begin_src emacs-lisp

;; Persist history over Emacs restarts. Vertico sorts by history position.
(use-package savehist
  :init
  (savehist-mode))

;; Emacs minibuffer configurations.
(use-package emacs
  :custom
  ;; Support opening new minibuffers from inside existing minibuffers.
  (enable-recursive-minibuffers t)
  ;; Hide commands in M-x which do not work in the current mode.  Vertico
  ;; commands are hidden in normal buffers. This setting is useful beyond
  ;; Vertico.
  (read-extended-command-predicate #'command-completion-default-include-p)
  ;; Do not allow the cursor in the minibuffer prompt
  (minibuffer-prompt-properties
   '(read-only t cursor-intangible t face minibuffer-prompt)))
#+end_src

* Which Key
#+begin_src emacs-lisp

;; which-key is installed after emacs30

(use-package which-key
  :demand t
  :init
  (which-key-mode)
  :config
  (setq which-key-idle-delay 1))
#+end_src

* Org Mode
;; Org mode --------------------
** Custom Functions
I want to configure some functions for use when loading.

*** Org Load
#+begin_src emacs-lisp

; setup functions to be called during package load
(defun tes/org-mode-setup ()
  (org-indent-mode)
  (visual-line-mode 1))
#+end_src

*** Org Face Setup
Setting up for different faces at different levels of the outline, so the sizes vary.

#+begin_src emacs-lisp
; setup function for font-setup in org
(defun tes/org-font-setup () (dolist (face '((org-level-1 . 1.5)
					     (org-level-2 . 1.3)
					     (org-level-3 . 1.2)
					     (org-level-4 . 1.1)
					     (org-level-5 . 1.1)
					     (org-level-6 . 1.1)
					     (org-level-7 . 1.1)
					     (org-level-8 . 1.1)))
			       (set-face-attribute (car face) nil :weight 'bold :height (cdr face))))
#+end_src

*** Insert Created Property into book-list items
#+begin_src emacs-lisp

; a custom function for myself
; to auto add a property of the created time to new headings use
; heading of file to set :: #+PROPERTY: CREATED nil
(defun tes/org-set-created-property ()
  "Set the CREATED property of an Org heading when it is first created."
  (when (and (org-at-heading-p)
	     (let (flag)
	       (with-current-buffer (current-buffer)
		 (when (boundp 'tes-created-flag)
		   (setq flag (symbol-value 'tes-created-flag))))
	       flag)
	     (org-set-property "CREATED" (format-time-string "[%Y-%m-%d]")))))
#+end_src

** Org use-package call

Setting hooks
- org-mode to org-mode-setup
- org-insert-heading to tes/org-set-created-property

  Binding keys

  Setq for variables.

  
#+begin_src emacs-lisp

  ;; org --- use-package call
  (use-package org
    :init
    (setq org-directory "~/Dropbox/Org/")
    (setq org-agenda-files (list (expand-file-name "Agenda/" org-directory)))
    :hook ((org-mode . tes/org-mode-setup)
  	 (org-insert-heading . tes/org-set-created-property))

    :bind (("C-c l" . org-store-link)
           ("C-c a" . org-agenda)
           ("C-c c" . org-capture))

    :config (setq
  	   org-special-ctrl-a/e t
  	   org-use-speed-commands t
  	   org-insert-heading-respect-content t
  	   org-M-RET-may-split-line '((default . nil))

  	   ;; double spacing
  	   sentence-end-double-space nil
  	   
  	   ;; logging
  	   org-log-done 'time
  	   org-log-into-drawer t

  	   ;; agenda warning day
  	   org-deadline-warning-days 3
  	   
  	   ;; Org styling, hide markup etc.
  	   org-pretty-entities t
  	   org-ellipsis "…"

  	   ;; jumping to locations C-c C-j org-goto function
  	   org-goto-interface 'outline-path-completion
  	   org-outline-path-complete-in-steps nil
  	   
  	   ;; Todo keywords  
  	   org-todo-keywords
  	   '((sequence "TODO(t)" "WAIT(w!)"  "|" "CANCEL(c@)" "DONE(d!)"))

  	   ;; Capture templates
  	   org-capture-templates
  	   '(("t" "Personal todo" entry
  	      (file+headline "Agenda/todo.org" "Inbox")
  	      "* TODO %?\n %i\n" :prepend t)
  	     ("i" "Idea" entry
  	      (file+headline "Agenda/todo.org" "Idea")
  	      "* IDEA %?\n %i\n" :prepend t))

  	   ;; consider adding to templates with one for meeting notes, that also goes to the journal file
  	   org-archive-location "archive.org::datetree//")

    (tes/org-font-setup))
#+end_src
   
* Magit
install magit
#+begin_src emacs-lisp

;; magit --- configuration
(use-package magit)
#+end_src

* Ediff
#+begin_src emacs-lisp

;; ediff --- configuration
(setq ediff-split-window-function 'split-window-horizontally)
(setq ediff-window-setup-function 'ediff-setup-windows-plain)
#+end_src

* Org Subpackages and Extensions
** Org-Journal
Org journal tryout.
#+begin_src emacs-lisp

;; org-journal setup
(use-package org-journal
  :ensure t
  :defer t
  :init
  ;; Change default prefix key; needs to be set before loading org-journal
  (setq org-journal-prefix-key "C-c j ")
  :config
  (setq org-journal-dir "~/Dropbox/Org/Journal"
        org-journal-date-format "%A, %d %B %Y"))
#+end_src
