#+title: Config
#+PROPERTY: header-args :tangle "test.el"


* Front Matter from Doom Config

** Identification
;; Some functionality uses this to identify you, e.g. GPG configuration, email
;; clients, file templates and snippets. It is optional.
;; (setq user-full-name "John Doe"
;;       user-mail-address "john@doe.com")

** Basic Fonts
;; Doom exposes five (optional) variables for controlling fonts in Doom:
;;
;; - `doom-font' -- the primary font to use
;; - `doom-variable-pitch-font' -- a non-monospace font (where applicable)
;; - `doom-big-font' -- used for `doom-big-font-mode'; use this for
;;   presentations or streaming.
;; - `doom-symbol-font' -- for symbols
;; - `doom-serif-font' -- for the `fixed-pitch-serif' face
;;
;; See 'C-h v doom-font' for documentation and more examples of what they
;; accept. For example:
;;

#+begin_src emacs-lisp
(setq doom-font (font-spec :family "Iosevka" :size 16 :weight 'semi-light)
      doom-variable-pitch-font (font-spec :family "ETBembo" :size 16))
      ;; doom-symbol-font (font-spec :family "Symbols Nerd Font"))
#+end_src

;;
;; If you or Emacs can't find your font, use 'M-x describe-font' to look them
;; up, `M-x eval-region' to execute elisp code, and 'M-x doom/reload-font' to
;; refresh your font settings. If Emacs still can't find your font, it likely
;; wasn't installed correctly. Font issues are rarely Doom issues!

** Doom Themes

;; There are two ways to load a theme. Both assume the theme is installed and
;; available. You can either set `doom-theme' or manually load a theme with the
;; `load-theme' function. This is the default:
#+begin_src emacs-lisp
(setq doom-theme 'doom-fairy-floss)
#+end_src

** Line Numbers
;; This determines the style of line numbers in effect. If set to `nil', line
;; numbers are disabled. For relative line numbers, set this to `relative'.
#+begin_src emacs-lisp
dk(setq display-line-numbers-type t)
#+end_src

** Org Directory Pre-Set
;; If you use `org' and don't want your org files in the default location below,
;; change `org-directory'. It must be set before org loads!
#+begin_src emacs-lisp
(setq org-directory "~/Dropbox/Org/")
#+end_src

** How to Config Packages
;; Whenever you reconfigure a package, make sure to wrap your config in an
;; `after!' block, otherwise Doom's defaults may override your settings. E.g.
;;
;;   (after! PACKAGE
;;     (setq x y))
;;
;; The exceptions to this rule:
;;
;;   - Setting file/directory variables (like `org-directory')
;;   - Setting variables which explicitly tell you to set them before their
;;     package is loaded (see 'C-h v VARIABLE' to look up their documentation).
;;   - Setting doom variables (which start with 'doom-' or '+').
;;
;; Here are some additional functions/macros that will help you configure Doom.
;;
;; - `load!' for loading external *.el files relative to this one
;; - `use-package!' for configuring packages
;; - `after!' for running code after a package has loaded
;; - `add-load-path!' for adding directories to the `load-path', relative to
;;   this file. Emacs searches the `load-path' when you load packages with
;;   `require' or `use-package'.
;; - `map!' for binding new keys

* Keybindings
#+begin_src emacs-lisp
(map! "C-x C-r" #'consult-recent-file)
#+end_src

* Doom Modeline
#+begin_src emacs-lisp
(use-package! doom-modeline
  :config
  (setq doom-modeline-enable-word-count t))  ;; Enables word count in modeline
#+end_src

* Org Mode
Settings for:
- org-todo-keywords. This could use some more cleanup.
- org-capture-templates.
- org-archive-location. I want items to go to the archive.org file by datetree
- org-tab-first-hook. Needed to remove so that I could get full cycling on tabs.
- faces for org headings. Setting the sizes for all headings.

To do:
- org-use-speed-commands
- (setq org-special-ctrl-k t) : changes behavior of kill line to ignore tags on first press in headline, so only edits the text
-
#+begin_src emacs-lisp
(after! org
   (setq org-todo-keywords
       '((sequence "TODO(t)" "PROJ(p)" "NEXT(n)" "WAIT(w)" "HOLD(h)" "IDEA(i)" "|" "MTGN(m)" "DONE(d)" "KILL(k)")
          (sequence "[ ](T)" "[-](S)" "[?](W)" "|" "[X](D)")
          (sequence "|" "OKAY(o)" "YES(y)" "NO(n)")))
   (setq org-capture-templates
         '(("t" "Personal todo" entry
            (file+headline +org-capture-todo-file "Inbox")
           "* TODO %?\n %i\n %a" :prepend t)
           ("j" "Journal" entry
            (file+olp+datetree +org-capture-journal-file)
            "* %U %?\n %i\n %a" :prepend t)
         ))
   (setq org-archive-location "archive.org::datetree//")
   (map! "C-c l" #'org-store-link
         "C-c a" #'org-agenda
         "C-c c" #'org-capture)
   (remove-hook 'org-tab-first-hook #'+org-cycle-only-current-subtree-h)
   (dolist (face '((org-level-1 . 1.5)
                  (org-level-2 . 1.3)
                  (org-level-3 . 1.2)
                  (org-level-4 . 1.1)
                  (org-level-5 . 1.1)
                  (org-level-6 . 1.1)
                  (org-level-7 . 1.1)
                  (org-level-8 . 1.1)))
    (set-face-attribute (car face) nil :weight 'bold :height (cdr face))))
#+end_src

** Org Modern - not working
  ;; (use-package! org-modern
  ;;   :config
  ;;   (setq
  ;;    org-auto-align-tags t
  ;;    org-tags-column t
  ;;    org-fold-catch-invisible-edits 'show-and-error
  ;;    org-special-ctrl-a/e t
  ;;    org-insert-heading-respect-content t))
  ;; (use-package! org-superstar
  ;;   :config
  ;;   (org-superstar-configure-like-org-bullets)))
  ;;(setq org-superstar-leading-bullet " ")
  ;;(setq org-superstar-special-todo-items t))
